version: '3.8'

services:
    otto:
        build:
            context: back/services/otto
            dockerfile: Dockerfile.dev
            args:
                - PORT=6666
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 6666
            REDIS_URL: redis://redis:6379
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Otto
            MONGODB_URI_TEST: mongodb://mongo:27017/OttoTest
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
        ports:
            - '6666:6666'
            - '9229:9229'
        volumes:
            - ./back/services/otto:/usr/src/otto
        depends_on:
            - redis
            - mongo
    goulag:
        build:
            context: back/services/goulag
            dockerfile: Dockerfile.dev
            args:
                - PORT=5002
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5002
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJnb3VsYWcifQ.9QX913j_OmzFyr7y6Z82gxAxkhusT_WGqOdAdaLmuFg
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Goulag
            MONGODB_URI_TEST: mongodb://mongo:27017/GoulagTest
            DOCUMENTATION_USER: admin
            PROFESOR_URL: http://profesor:5001
            DOCUMENTATION_PASSWORD: admin
            BOUNCER_URL: http://bouncer:5008
            PROSPECTIN_URL: https://staging-prospectin-api.herokuapp.com
            PROSPECTIN_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1ZTgxZDc5MmQzYmZiMzAwMTdhOGQ0NjAiLCJsaW5rZWRpbklkIjoiODA0NzgyNzY1In0.PP_EByIAHezFb88FNIR41OQWEd26BNckGFIzItnbDec
        ports:
            - '5002:5002'
        volumes:
            - ./back/services/goulag:/usr/src/goulag
        depends_on:
            - redis
            - mongo
            - otto
    profesor:
        build:
            context: back/services/profesor
            dockerfile: Dockerfile.dev
            args:
                - PORT=5001
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5001
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJwcm9mZXNvciJ9.vGARs6kAgyviA-rq7ldlP4Fqxsnpgq_o3Bsd04_T2bQ
            GOULAG_BASE_URL: http://goulag:5002/graphql
            SHIVA_BASE_URL: http://shiva:5003
            ENUTROF_BASE_URL: http://enutrof:5005
            HERMES_BASE_URL: http://hermes:5004
            BOUNCER_API_URL: http://bouncer:5008
            JANUS_URL: http://janus:5010
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Profesor
            MONGODB_URI_TEST: mongodb://mongo:27017/ProfesorTest
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
            LIFELINE_TOKEN: token
            ADMIN_API_KEY: 4aecf7c8-efae-42ce-8ba0-da8a89eb0044
            SLEEP_TIME_UNIT: seconds
        ports:
            - '5001:5001'
        volumes:
            - ./back/services/profesor:/usr/src/profesor
        depends_on:
            - redis
            - mongo
            - otto
    stargate:
        build:
            context: back/services/stargate
            dockerfile: Dockerfile.dev
            args:
                - PORT=5000
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5000
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJzdGFyZ2F0ZSJ9.y8VIfAsWL22nlpWMWKsv_9ebUCJ1xziQ1Qh6srjMTg8
            GOULAG_URL: http://goulag:5002
            PROFESOR_URL: http://profesor:5001
            SHIVA_URL: http://shiva:5003
            HERMES_URL: http://hermes:5004
            VOLTAIRE_URL: http://voltaire:5006
            ZILEAN_URL: http://zilean:5007
            JANUS_URL: http://janus:5010
            BOUNCER_URL: http://bouncer:5008
            HAWKING_URL: http://hawking:5009
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Stargate
            MONGODB_URI_TEST: mongodb://mongo:27017/StargateTest
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
            LIFELINE_API_KEY: token
            TRADUORA_URL: https://shakespeare-v2.herokuapp.com
            TRADUORA_PROJECT_ID: baab9752-e91c-4a73-90a1-65d80caf6fb2
            TRADUORA_CLIENT_ID: 21e06f2a-7169-4d5d-928d-69ee0bbdf0f2
            TRADUORA_CLIENT_SECRET: eZx3AQr56PuHeF3tAlK3GjyB6Slqk8rx
            WAAPI_API_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmF0aW9uRGF0ZSI6IjI5OTktMTItMzFUMjM6NTk6NTkuOTk5WiIsInNhbHQiOiJub25lIiwianRpIjoiMzhlMzM5ZGQtNTY0Zi00ZGIyLTk3OTAtMjllNmJkMTQ0ZTk5IiwiaWF0IjoxNjAyMDY2NDg4LCJleHAiOjE2MDIwNzAwODh9.D654ITgsba7ffui-T4_4Pa1CtkI7nEEJkWcMsIs75aw
        ports:
            - '5000:5000'
        volumes:
            - ./back/services/stargate:/usr/src/stargate
        depends_on:
            - redis
            - mongo
            - otto
            - bouncer
    shiva:
        build:
            context: back/services/shiva
            dockerfile: Dockerfile.dev
            args:
                - PORT=5003
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5003
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            ZILEAN_BASE_URL: http://zilean:5007
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJzdGFyZ2F0ZSJ9.y8VIfAsWL22nlpWMWKsv_9ebUCJ1xziQ1Qh6srjMTg8
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Shiva
            MONGODB_URI_TEST: mongodb://mongo:27017/ShivaTest
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
            GOULAG_URL: http://goulag:5002/graphql
            BOUNCER_API_URL: http://bouncer:5008
            LIFELINE_TOKEN: token
        ports:
            - '5003:5003'
        volumes:
            - ./back/services/shiva:/usr/src/shiva
        depends_on:
            - redis
            - mongo
            - otto
    hermes:
        build:
            context: back/services/hermes
            dockerfile: Dockerfile.dev
            args:
                - PORT=5004
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5004
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            ZILEAN_BASE_URL: http://zilean:5007
            GOULAG_BASE_URL: http://goulag:5002/graphql
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJzdGFyZ2F0ZSJ9.y8VIfAsWL22nlpWMWKsv_9ebUCJ1xziQ1Qh6srjMTg8
            SECRET: kzenjf68zef/*zef-gergrege
            GOOGLE_CLIENT_ID: 141637350927-kfbhgp5p13tf9r5e9c2vlr7cid20m19u.apps.googleusercontent.com
            GOOGLE_CLIENT_SECRET: B29hgBJUFUOQF2tRsZtxeyPI
            MYSTIQUE_URL: http://localhost:3000
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Hermes
            MONGODB_URI_TEST: mongodb://mongo:27017/HermesTest
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
            SALT_TOKEN: kzenj62-f68zef/*zef-g:th1ge4
            LIFELINE_TOKEN: token
        ports:
            - '5004:5004'
        volumes:
            - ./back/services/hermes:/usr/src/hermes
        depends_on:
            - redis
            - mongo
            - otto
    hermes-daemon:
        build:
            context: back/services/hermes-daemon
            dockerfile: Dockerfile.dev
            args:
                - PORT=8887
        environment:
            NODE_ENV: E2E
            REDIS_URL: redis://redis:6379
            PORT: 8887
            HERMES_URL: http://hermes:8888
            BOUNCER_URL: http://bouncer:5008
            VOLTAIRE_URL: http://voltaire:5006
            HERMES_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.Imhlcm1lcy1kYWVtb24i.z6F4vTt-Xm080WPkEm1CW1kC7KHzE7VtcdVheHYlcYE
            HERMES_SECRET: kzenjf68zef/*zef-gergrege
            SEND_MAILS_INTERVAL: 1
            FETCH_MAILS_INTERVAL: 30
        ports:
            - '8887:8887'
        volumes:
            - ./back/services/hermes-daemon:/usr/src/hermes-daemon
        depends_on:
            - redis
            - mongo
            - bouncer
            - hermes
    enutrof:
        build:
            context: back/services/enutrof
            dockerfile: Dockerfile.dev
            args:
                - PORT=5005
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5005
            REDIS_URL: redis://redis:6379
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Enutrof
            MONGODB_URI_TEST: mongodb://mongo:27017/EnutrofTest
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
            OTTO_URL: ws://otto:6666
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJlbnV0cm9mIn0.jD0AkKiPFtigpe8VwUgX7qzWonbd2dfF3eQ5Nd1n3S8
            E2E_EXTERNAL_API: http://chameleon:6458
            DROP_CONTACT_API_KEY: 'e2e-test'
            ENRICHMENT_CREATION_MAX_INTERVAL: 1000
            MAX_GET_BATCH_RESPONSE_ITERATIONS: 5
            GET_BATCH_RESPONSE_INTERVAL: 200
        ports:
            - '5005:5005'
        volumes:
            - ./back/services/enutrof:/usr/src/enutrof
        depends_on:
            - redis
            - mongo
            - otto
    voltaire:
        build:
            context: back/services/voltaire
            dockerfile: Dockerfile.dev
            args:
                - PORT=5006
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5006
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJ2b2x0YWlyZSJ9.VGRQLYaML3JazCMTpsiGjrK4dLgCGE2msJo8lll3RhM
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Voltaire
            MONGODB_URI_TEST: mongodb://mongo:27017/VoltaireTest
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
        ports:
            - '5006:5006'
        volumes:
            - ./back/services/voltaire:/usr/src/voltaire
        depends_on:
            - redis
            - mongo
            - otto
    zilean:
        build:
            context: back/services/zilean
            dockerfile: Dockerfile.dev
            args:
                - PORT=5007
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5007
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJ6aWxlYW4ifQ.RxLoMQRvjv5FTmHebvIQcHEWHAYsNJBWNFczZck1tgA
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Zilean
            MONGODB_URI_TEST: mongodb://mongo:27017/ZileanTest
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
        ports:
            - '5007:5007'
        volumes:
            - ./back/services/zilean:/usr/src/zilean
        depends_on:
            - redis
            - mongo
            - otto
    bouncer:
        build:
            context: back/services/bouncer
            dockerfile: Dockerfile.dev
            args:
                - PORT=5008
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5008
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            KAUPAONA_API_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoid2FhbGF4eSIsImNyZWF0ZWREYXRlIjoxNjE4OTk4MDk5NDkwfQ.sddnQYapd2VBwXN6aOl2nPEGc8PwJt87xl_xbnfrmAo
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJib3VuY2VyIn0.rv0NYsD4M4rPfHvf96KiN0LuOriPyuJxqWVd1961xNc
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Bouncer
            MONGODB_URI_TEST: mongodb://mongo:27017/BouncerTest
            WAAPI_API_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmF0aW9uRGF0ZSI6IjI5OTktMTItMzFUMjM6NTk6NTkuOTk5WiIsInNhbHQiOiJub25lIiwianRpIjoiMzhlMzM5ZGQtNTY0Zi00ZGIyLTk3OTAtMjllNmJkMTQ0ZTk5IiwiaWF0IjoxNjAyMDY2NDg4LCJleHAiOjE2MDIwNzAwODh9.D654ITgsba7ffui-T4_4Pa1CtkI7nEEJkWcMsIs75aw
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
            MIRAGE_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmF0aW9uRGF0ZSI6IjIxMjAtMDMtMzFUMTY6NDI6MjYuNDYzWiIsInBlcm1pc3Npb25zIjpbIlNhYVNUb2tlbiJdfQ.yCvExMyJ8CBvRsfjRsD6eAaQrajkjnj9mFlV3iP4S4A
            PROSPECTIN_MIRAGE_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmF0aW9uRGF0ZSI6IjIxMTktMTEtMTRUMTU6MTE6NTQuMzMxWiIsInBlcm1pc3Npb25zIjpbIlNhYVNUb2tlbiJdfQ.Q6cI6GBT77tbRxXQndwlNDAbeO1JtwfFUFPoDsWiois
            LIFELINE_TOKEN: token
        ports:
            - '5008:5008'
        volumes:
            - ./back/services/bouncer:/usr/src/bouncer
        depends_on:
            - redis
            - mongo
            - otto
    hawking:
        build:
            context: back/services/hawking
            dockerfile: Dockerfile.dev
            args:
                - PORT=5009
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5009
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJoYXdraW5nIn0.Nr8Bv9eeUNs_aYQ-f0xNr-A9-MwetasfYrlycCg16tU
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Hawking
            MONGODB_URI_TEST: mongodb://mongo:27017/HawkingTest
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
            SLACK_TOKEN: cce9bdbb82c6919c26c725f18812414fbb5894f872a20f042e938af246bd743e
            SLACK_KPI_CHANNEL: C01T62UJJ94
        ports:
            - '5009:5009'
        volumes:
            - ./back/services/hawking:/usr/src/hawking
        depends_on:
            - redis
            - mongo
            - otto
    janus:
        build:
            context: back/services/janus
            dockerfile: Dockerfile.dev
            args:
                - PORT=5010
                - NPM_TOKEN=0bac5327-18e7-4495-82ba-c5e40b5712d5
        environment:
            PORT: 5010
            REDIS_URL: redis://redis:6379
            OTTO_URL: ws://otto:6666
            OTTO_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRob3IiOiJqYW51cyJ9.2uvHhq148S8zFaq7Ck-B7lFC8vNpldsUwP2d1Qe2wKY
            NODE_ENV: E2E
            MONGODB_URI: mongodb://mongo:27017/Janus
            MONGODB_URI_TEST: mongodb://mongo:27017/JanusTest
            DOCUMENTATION_USER: admin
            BOUNCER_URL: http://bouncer:5008
            DOCUMENTATION_PASSWORD: admin
            WEB_CONCURRENCY: 2
        ports:
            - '5010:5010'
        volumes:
            - ./back/services/janus:/usr/src/janus
        depends_on:
            - redis
            - mongo
            - otto
    mongo:
        image: mongo:latest
        volumes:
            - mongodata:/data/db
        ports:
            - '27017:27017'
        logging:
            driver: none
    redis:
        image: redis:latest
        command: ['redis-server', '--bind', 'redis', '--port', '6379']
        volumes:
            - ~/RedisDB/data:/data/db
        ports:
            - '6379:6379'
        logging:
            driver: none

volumes:
    mongodata:
